// MOVIES
const GET_MOVIES = 'GET_MOVIES';
const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

// FILTER
const FILTER_BY = 'FILTER_BY';

// SORT
const SORT_BY = 'SORT_BY';

// SEARCH
const SEARCH_BY = 'SEARCH_BY';

export default {
  GET_MOVIES,
  GET_MOVIES_SUCCESS,
  GET_MOVIES_ERROR,
  GET_MOVIES_REQUEST,
  SEARCH_BY,
  SORT_BY,
  FILTER_BY
};
