// MOVIES
const GET_MOVIES = 'GET_MOVIES';
const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

// MOVIE
const ADD_MOVIE = 'ADD_MOVIE';
const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
const ADD_MOVIE_ERROR = 'ADD_MOVIE_ERROR';

const EDIT_MOVIE = 'EDIT_MOVIE';
const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS';
const EDIT_MOVIE_ERROR = 'EDIT_MOVIE_ERROR';

const DELETE_MOVIE = 'DELETE_MOVIE';
const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
const DELETE_MOVIE_ERROR = 'DELETE_MOVIE_ERROR';

const SHOW_MOVIE_DETAILS = 'SHOW_MOVIE_DETAILS';
const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
const GET_MOVIE_DETAILS_REQUEST = 'GET_MOVIE_DETAILS_REQUEST';
const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
const GET_MOVIE_DETAILS_ERROR = 'GET_MOVIE_DETAILS_ERROR';

// FILTER
const FILTER_BY = 'FILTER_BY';

// SORT
const SORT_BY = 'SORT_BY';

// SEARCH
const SEARCH_BY = 'SEARCH_BY';

export default {
  GET_MOVIES,
  GET_MOVIES_SUCCESS,
  GET_MOVIES_ERROR,
  GET_MOVIES_REQUEST,
  SEARCH_BY,
  SORT_BY,
  FILTER_BY,
  ADD_MOVIE,
  ADD_MOVIE_SUCCESS,
  ADD_MOVIE_ERROR,
  EDIT_MOVIE,
  EDIT_MOVIE_SUCCESS,
  EDIT_MOVIE_ERROR,
  DELETE_MOVIE,
  DELETE_MOVIE_SUCCESS,
  DELETE_MOVIE_ERROR,
  SHOW_MOVIE_DETAILS,
  GET_MOVIE_DETAILS,
  GET_MOVIE_DETAILS_REQUEST,
  GET_MOVIE_DETAILS_SUCCESS,
  GET_MOVIE_DETAILS_ERROR
};
